### ISSUE TITLE
don't receive information channel

### ISSUE THREAD

**Issue by barto95100** [custom-components/youtube#15]
I configure the addon but nothing to do ? it's possible to add More channel ID ? 

thank's for the addon 👍

**Comment by barto95100** [comment]
@ludeeus  possible to respond me please ?

**Comment by pinkywafer** [comment]
make sure that you have configures the sensors in your configuration.yaml file.  Here is an example:
```yaml
sensor:
  - platform: youtube
    channel_id: UCtI0Hodo5o5dUb67FeUjDeA
```
this would set up an entity called: `sensor.spacex` as it is the spaceX channel
if you want to monitor more than one channel, simply repeat the last two lines under the `sensor: ` section, ie:
```yaml
sensor:
  - platform: youtube
    channel_id: UCtI0Hodo5o5dUb67FeUjDeA
  - platform: youtube
    channel_id: nextChannelId
```
and continue in this manner
